# 线性代数

## 标量

In [46]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量

In [47]:
# 使用torch.arange创建一个长度为4的一维张量,包含0到3的整数序列 
x = torch.arange(4)
x, x[3], len(x), x.shape

(tensor([0, 1, 2, 3]), tensor(3), 4, torch.Size([4]))

## 矩阵

In [48]:
# 创建一个5x4矩阵 
A = torch.arange(20).reshape(5, 4)
# A和A的转置
A, A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [49]:
# 对称矩阵
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

## 张量

In [50]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B, A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [51]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
# 标量和张量的运算,会作用在张量的每一个位置 | 计算结果形状不变,仍然是2 x 3 x 4
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维

In [52]:
# 将张量x的数据类型设置为32位浮点型(float32)
x = torch.arange(4, dtype=torch.float32)
# 降维求和 | 不加参数使用sum()会将tensor降维到一个scalar
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [53]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [54]:
# axis=0表示沿着第一个轴降维求和
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [55]:
# axis=1表示沿着第二个轴降维求和
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [56]:
# 沿着行和列对矩阵求和
A.sum(axis=[0, 1])  # 结果和A.sum()相同


tensor(190.)

In [57]:
# 计算张量平均值 | numel()返回张量元素总数
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [58]:
# 沿轴0计算张量平均值
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [59]:
# 非降维求和
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [60]:
# 归一化（广播机制）
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [61]:
# 计算张量的累加和
A, A.cumsum(axis=0)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.],
         [24., 28., 32., 36.],
         [40., 45., 50., 55.]]))

## 点积

In [62]:
y = torch.ones(4, dtype = torch.float32)
# 点积
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [63]:
# 按元素乘法，然后进行求和表示两个向量的点积
torch.sum(x * y)

tensor(6.)

## 矩阵-向量积

In [64]:
# 矩阵-向量乘法
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵-矩阵积

In [65]:
# 矩阵-矩阵乘法
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数

In [66]:
u = torch.tensor([3.0, -4.0])
# torch.norm计算的是u的L2范数(默认情况下),即u中每个元素平方和开根号
torch.norm(u)

tensor(5.)

In [67]:
# L1范数的计算方式是所有元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [68]:
# 类似于向量的范数,矩阵的Frobenius范数是矩阵元素平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)