# 图像卷积

In [44]:
import torch
from torch import nn
from d2l import torch as d2l

def corr2d(X, k):
    h, w = k.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i+h, j:j+w] * k).sum()
    return Y

In [45]:
X = torch.arange(9).reshape(3,3).float()
k = torch.arange(4).reshape(2,2).float()
corr2d(X, k)

tensor([[19., 25.],
        [37., 43.]])

In [46]:
class Conv2D(nn.Module):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.weight = nn.Parameter(torch.rand(kernel_szie))
        self.bias = nn.Parameter(torch.zeros(1))
    
    def forward(self, x):
        return corr2d(x, self.weight) + self.bias

In [47]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
X

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [48]:
K = torch.tensor([[1.0, -1.0]])

In [49]:
Y = corr2d(X, K)
Y 

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [50]:
conv2d = nn.Conv2d(1,1,kernel_size=(1,2), bias=False)
X = X.reshape(1,1,6,8)
Y = Y.reshape(1,1,6,7)
for i in range(20):
    y_hat = conv2d(X)
    loss = (y_hat - Y) ** 2
    conv2d.zero_grad()
    loss.sum().backward()
    conv2d.weight.data[:] -= 3e-2 * conv2d.weight.grad
    if (i+1) % 2 == 0:
        print(f'batch {i+1}, loss {loss.sum():.3f}, {conv2d.weight.data.reshape(1,2)}')

batch 2, loss 7.790, tensor([[ 0.4555, -0.9101]])
batch 4, loss 2.478, tensor([[ 0.7246, -1.0155]])
batch 6, loss 0.895, tensor([[ 0.8537, -1.0399]])
batch 8, loss 0.347, tensor([[ 0.9186, -1.0378]])
batch 10, loss 0.139, tensor([[ 0.9529, -1.0292]])
batch 12, loss 0.056, tensor([[ 0.9719, -1.0207]])
batch 14, loss 0.023, tensor([[ 0.9829, -1.0141]])
batch 16, loss 0.009, tensor([[ 0.9894, -1.0094]])
batch 18, loss 0.004, tensor([[ 0.9934, -1.0061]])
batch 20, loss 0.002, tensor([[ 0.9958, -1.0040]])
