# 循环神经网络

## 有隐状态的循环神经网络
<img src="./image/8.4_1RecurrentNeuralNetworksWithHiddenStates.png" width=400>

具有隐状态的循环神经网络

In [4]:
import torch
from d2l import torch as d2l

X, W_xh = torch.normal(0, 1, (3, 1)), torch.normal(0, 1, (1, 4))
H, W_hh = torch.normal(0, 1, (3, 4)), torch.normal(0, 1, (4, 4))
print(X,W_xh)
torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

tensor([[ 0.7483],
        [ 0.3282],
        [-0.8038]]) tensor([[ 1.2905, -0.2572, -0.1331, -0.5072]])


tensor([[-2.0807, -6.7683, -2.3877,  0.7904],
        [ 2.9395, -1.4448,  3.9111,  1.2907],
        [-3.9346, -0.9520, -1.8541,  0.0718]])

In [2]:
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[-1.4240, -1.7710, -3.2678,  0.7838],
        [ 1.7570,  3.6908, -1.8655, -2.5950],
        [ 0.2629,  0.4448, -0.1413, -0.0454]])

## 基于循环神经网络的字符级语言模型
<img src="./image/8.4_2Character-levelLanguageModelBasedOnRecurrentNeuralNetworks.png" width=400>

<text>输入序列和标签序列分别为“machin”和“achine”</text>

## 困惑度（Perplexity）